{{ config(materialized='view') }}

SELECT
    O_ORDERKEY,
    O_ORDERDATE,
    O_CUSTKEY,
    SUM(O_TOTALPRICE - PS_SUPPLYCOST) AS Total_Profit
FROM
    fact_orders_line
JOIN
    PARTSUPP USING (PS_PARTKEY, PS_SUPPKEY)
JOIN
    ORDERS USING (O_ORDERKEY)
WHERE
    O_ORDERDATE BETWEEN '1994-01-01' AND '1995-12-31'
GROUP BY
    O_ORDERKEY, O_ORDERDATE, O_CUSTKEY;
