With lineitem AS (
   SELECT
      L_ORDERKEY,L_PARTKEY,L_SUPPKEY,
      L_LINENUMBER,L_QUANTITY,L_EXTENDEDPRICE,
      L_DISCOUNT,L_TAX,L_RETURNFLAG,L_LINESTATUS,
      L_SHIPDATE,L_COMMITDATE,L_RECEIPTDATE,
      L_SHIPINSTRUCT,L_SHIPMODE     
   FROM tpch.lineitem
)

Select * from lineitem